global:
  scrape_interval: 5s # Scrape metrics every 5 seconds

scrape_configs:
  - job_name: 'ledger-api'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['app:8080'] # This matches your Spring Boot service name in docker-compose