# Name the application
spring.application.name=ledger-api

# Force Micrometer to tag all metrics with this application name (Crucial for Dashboard 4701)
management.metrics.tags.application=${spring.application.name}
# Tell Spring Boot how to connect to your Docker PostgreSQL database
spring.datasource.url=jdbc:postgresql://localhost:5432/ledger
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# SDE 2 Magic: Tell Hibernate to automatically create the 'users' and 'wallets' tables based on your Java Entities
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Optional: Run Tomcat on port 8080 (default)
server.port=8080

# SDE 2 Observability: Expose Prometheus metrics
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true

# SDE 2 Event-Driven Architecture: Kafka Configuration
spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer